<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aigamo.MatchGenerator" />
		<Using Include="Aigamo.MatchGenerator" />
		<PackageReference Include="Aigamo.Results" />
		<Using Include="Aigamo.Results" />
	</ItemGroup>
</Project>
