// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.CivilRegistration.Infrastructure.Persistence;

#nullable disable

namespace WebApp.CivilRegistration.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415140009_UseTablePerTypeMappingStrategy")]
    partial class UseTablePerTypeMappingStrategy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("WebApp_CivilRegistration")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DeathCertificates.Entities.DeathCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeceasedId")
                        .HasColumnType("int");

                    b.Property<int?>("WidowedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId");

                    b.HasIndex("WidowedId");

                    b.ToTable("DeathCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DivorceCertificates.Entities.DivorceCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarriageCertificateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarriageCertificateId");

                    b.ToTable("DivorceCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Person1Id")
                        .HasColumnType("int");

                    b.Property<int>("Person2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Person1Id");

                    b.HasIndex("Person2Id");

                    b.ToTable("MarriageCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("MaritalStateMachines", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StateMachineId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateMachineId", "Version")
                        .IsUnique();

                    b.ToTable("MaritalStatuses", "WebApp_CivilRegistration");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Persons", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.DeceasedState", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.ToTable("DeceasedStates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.DivorcedState", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.ToTable("DivorcedStates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MarriedState", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.ToTable("MarriedStates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.SingleState", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.ToTable("SingleStates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.WidowedState", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.ToTable("WidowedStates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DeathCertificates.Entities.DeathCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Deceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Widowed")
                        .WithMany()
                        .HasForeignKey("WidowedId");

                    b.Navigation("Deceased");

                    b.Navigation("Widowed");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DivorceCertificates.Entities.DivorceCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", "MarriageCertificate")
                        .WithMany()
                        .HasForeignKey("MarriageCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageCertificate");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Person1")
                        .WithMany()
                        .HasForeignKey("Person1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Person2")
                        .WithMany()
                        .HasForeignKey("Person2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person1");

                    b.Navigation("Person2");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Person")
                        .WithOne("MaritalStateMachine")
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", "StateMachine")
                        .WithMany("States")
                        .HasForeignKey("StateMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateMachine");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.DeceasedState", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", null)
                        .WithOne()
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.DeceasedState", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.DeceasedStatePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("DeceasedStateId")
                                .HasColumnType("int");

                            b1.HasKey("DeceasedStateId");

                            b1.ToTable("DeceasedStates", "WebApp_CivilRegistration");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedStateId");

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.DeathInformation", "DeathInformation", b2 =>
                                {
                                    b2.Property<int>("DeceasedStatePayloadDeceasedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("DeathCertificateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("DeceasedAtAge")
                                        .HasColumnType("int");

                                    b2.HasKey("DeceasedStatePayloadDeceasedStateId");

                                    b2.HasIndex("DeathCertificateId");

                                    b2.ToTable("DeceasedStates", "WebApp_CivilRegistration");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.DeathCertificates.Entities.DeathCertificate", "DeathCertificate")
                                        .WithMany()
                                        .HasForeignKey("DeathCertificateId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("DeceasedStatePayloadDeceasedStateId");

                                    b2.Navigation("DeathCertificate");
                                });

                            b1.Navigation("DeathInformation")
                                .IsRequired();
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.DivorcedState", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", null)
                        .WithOne()
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.DivorcedState", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.DivorcedStatePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("DivorcedStateId")
                                .HasColumnType("int");

                            b1.HasKey("DivorcedStateId");

                            b1.ToTable("DivorcedStates", "WebApp_CivilRegistration");

                            b1.WithOwner()
                                .HasForeignKey("DivorcedStateId");

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.DivorceInformation", "DivorceInformation", b2 =>
                                {
                                    b2.Property<int>("DivorcedStatePayloadDivorcedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("DivorceCertificateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("DivorcedAtAge")
                                        .HasColumnType("int");

                                    b2.Property<int>("DivorcedFromId")
                                        .HasColumnType("int");

                                    b2.HasKey("DivorcedStatePayloadDivorcedStateId");

                                    b2.HasIndex("DivorceCertificateId");

                                    b2.HasIndex("DivorcedFromId");

                                    b2.ToTable("DivorcedStates", "WebApp_CivilRegistration");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.DivorceCertificates.Entities.DivorceCertificate", "DivorceCertificate")
                                        .WithMany()
                                        .HasForeignKey("DivorceCertificateId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "DivorcedFrom")
                                        .WithMany()
                                        .HasForeignKey("DivorcedFromId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("DivorcedStatePayloadDivorcedStateId");

                                    b2.Navigation("DivorceCertificate");

                                    b2.Navigation("DivorcedFrom");
                                });

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.MarriageInformation", "MarriageInformation", b2 =>
                                {
                                    b2.Property<int>("DivorcedStatePayloadDivorcedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriageCertificateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedAtAge")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedWithId")
                                        .HasColumnType("int");

                                    b2.HasKey("DivorcedStatePayloadDivorcedStateId");

                                    b2.HasIndex("MarriageCertificateId");

                                    b2.HasIndex("MarriedWithId");

                                    b2.ToTable("DivorcedStates", "WebApp_CivilRegistration");

                                    b2.WithOwner()
                                        .HasForeignKey("DivorcedStatePayloadDivorcedStateId");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", "MarriageCertificate")
                                        .WithMany()
                                        .HasForeignKey("MarriageCertificateId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "MarriedWith")
                                        .WithMany()
                                        .HasForeignKey("MarriedWithId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.Navigation("MarriageCertificate");

                                    b2.Navigation("MarriedWith");
                                });

                            b1.Navigation("DivorceInformation")
                                .IsRequired();

                            b1.Navigation("MarriageInformation")
                                .IsRequired();
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MarriedState", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", null)
                        .WithOne()
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.MarriedState", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.MarriedStatePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("MarriedStateId")
                                .HasColumnType("int");

                            b1.HasKey("MarriedStateId");

                            b1.ToTable("MarriedStates", "WebApp_CivilRegistration");

                            b1.WithOwner()
                                .HasForeignKey("MarriedStateId");

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.MarriageInformation", "MarriageInformation", b2 =>
                                {
                                    b2.Property<int>("MarriedStatePayloadMarriedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriageCertificateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedAtAge")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedWithId")
                                        .HasColumnType("int");

                                    b2.HasKey("MarriedStatePayloadMarriedStateId");

                                    b2.HasIndex("MarriageCertificateId");

                                    b2.HasIndex("MarriedWithId");

                                    b2.ToTable("MarriedStates", "WebApp_CivilRegistration");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", "MarriageCertificate")
                                        .WithMany()
                                        .HasForeignKey("MarriageCertificateId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("MarriedStatePayloadMarriedStateId");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "MarriedWith")
                                        .WithMany()
                                        .HasForeignKey("MarriedWithId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.Navigation("MarriageCertificate");

                                    b2.Navigation("MarriedWith");
                                });

                            b1.Navigation("MarriageInformation")
                                .IsRequired();
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.SingleState", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", null)
                        .WithOne()
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.SingleState", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.SingleStatePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("SingleStateId")
                                .HasColumnType("int");

                            b1.HasKey("SingleStateId");

                            b1.ToTable("SingleStates", "WebApp_CivilRegistration");

                            b1.WithOwner()
                                .HasForeignKey("SingleStateId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.WidowedState", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", null)
                        .WithOne()
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.WidowedState", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.WidowedStatePayload", "Payload", b1 =>
                        {
                            b1.Property<int>("WidowedStateId")
                                .HasColumnType("int");

                            b1.HasKey("WidowedStateId");

                            b1.ToTable("WidowedStates", "WebApp_CivilRegistration");

                            b1.WithOwner()
                                .HasForeignKey("WidowedStateId");

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.MarriageInformation", "MarriageInformation", b2 =>
                                {
                                    b2.Property<int>("WidowedStatePayloadWidowedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriageCertificateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedAtAge")
                                        .HasColumnType("int");

                                    b2.Property<int>("MarriedWithId")
                                        .HasColumnType("int");

                                    b2.HasKey("WidowedStatePayloadWidowedStateId");

                                    b2.HasIndex("MarriageCertificateId");

                                    b2.HasIndex("MarriedWithId");

                                    b2.ToTable("WidowedStates", "WebApp_CivilRegistration");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", "MarriageCertificate")
                                        .WithMany()
                                        .HasForeignKey("MarriageCertificateId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "MarriedWith")
                                        .WithMany()
                                        .HasForeignKey("MarriedWithId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("WidowedStatePayloadWidowedStateId");

                                    b2.Navigation("MarriageCertificate");

                                    b2.Navigation("MarriedWith");
                                });

                            b1.OwnsOne("WebApp.CivilRegistration.Domain.Persons.Entities.WidowhoodInformation", "WidowhoodInformation", b2 =>
                                {
                                    b2.Property<int>("WidowedStatePayloadWidowedStateId")
                                        .HasColumnType("int");

                                    b2.Property<int>("WidowedAtAge")
                                        .HasColumnType("int");

                                    b2.Property<int>("WidowedFromId")
                                        .HasColumnType("int");

                                    b2.HasKey("WidowedStatePayloadWidowedStateId");

                                    b2.HasIndex("WidowedFromId");

                                    b2.ToTable("WidowedStates", "WebApp_CivilRegistration");

                                    b2.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "WidowedFrom")
                                        .WithMany()
                                        .HasForeignKey("WidowedFromId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("WidowedStatePayloadWidowedStateId");

                                    b2.Navigation("WidowedFrom");
                                });

                            b1.Navigation("MarriageInformation")
                                .IsRequired();

                            b1.Navigation("WidowhoodInformation")
                                .IsRequired();
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.Person", b =>
                {
                    b.Navigation("MaritalStateMachine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
