// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.CivilRegistration.Infrastructure.Persistence;

#nullable disable

namespace WebApp.CivilRegistration.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250325125303_AddPayloadToMaritalStatus")]
    partial class AddPayloadToMaritalStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("WebApp_CivilRegistration")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("MaritalStateMachines", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("StateMachineId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateMachineId", "Version")
                        .IsUnique();

                    b.ToTable("MaritalStatuses", "WebApp_CivilRegistration");

                    b.HasDiscriminator().HasValue("MaritalStatus");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Persons", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus+Divorced", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.Property<string>("Payload")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext")
                        .HasColumnName("Payload");

                    b.HasDiscriminator().HasValue("Divorced");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus+Married", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.Property<string>("Payload")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext")
                        .HasColumnName("Payload");

                    b.HasDiscriminator().HasValue("Married");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus+Single", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.Property<string>("Payload")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext")
                        .HasColumnName("Payload");

                    b.HasDiscriminator().HasValue("Single");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus+Widowed", b =>
                {
                    b.HasBaseType("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus");

                    b.Property<string>("Payload")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("longtext")
                        .HasColumnName("Payload");

                    b.HasDiscriminator().HasValue("Widowed");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.Person", "Person")
                        .WithOne("MaritalStateMachine")
                        .HasForeignKey("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStatus", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", "StateMachine")
                        .WithMany("States")
                        .HasForeignKey("StateMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateMachine");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.MaritalStateMachine", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.Persons.Entities.Person", b =>
                {
                    b.Navigation("MaritalStateMachine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
