// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.CivilRegistration.Infrastructure.Persistence;

#nullable disable

namespace WebApp.CivilRegistration.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("WebApp_CivilRegistration")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DeathCertificates.Entities.DeathCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WidowedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedId");

                    b.HasIndex("WidowedId");

                    b.ToTable("DeathCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DivorceCertificates.Entities.DivorceCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarriageCertificateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarriageCertificateId");

                    b.ToTable("DivorceCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HusbandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WifeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HusbandId");

                    b.HasIndex("WifeId");

                    b.ToTable("MarriageCertificates", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.People.Entities.MaritalStateMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("States")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("MaritalStateMachines", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.People.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("People", "WebApp_CivilRegistration");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DeathCertificates.Entities.DeathCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.People.Entities.Person", "Deceased")
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.CivilRegistration.Domain.People.Entities.Person", "Widowed")
                        .WithMany()
                        .HasForeignKey("WidowedId");

                    b.Navigation("Deceased");

                    b.Navigation("Widowed");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.DivorceCertificates.Entities.DivorceCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", "MarriageCertificate")
                        .WithMany()
                        .HasForeignKey("MarriageCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageCertificate");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.MarriageCertificates.Entities.MarriageCertificate", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.People.Entities.Person", "Husband")
                        .WithMany()
                        .HasForeignKey("HusbandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.CivilRegistration.Domain.People.Entities.Person", "Wife")
                        .WithMany()
                        .HasForeignKey("WifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Husband");

                    b.Navigation("Wife");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.People.Entities.MaritalStateMachine", b =>
                {
                    b.HasOne("WebApp.CivilRegistration.Domain.People.Entities.Person", "Person")
                        .WithOne("MaritalStateMachine")
                        .HasForeignKey("WebApp.CivilRegistration.Domain.People.Entities.MaritalStateMachine", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WebApp.CivilRegistration.Domain.People.Entities.Person", b =>
                {
                    b.Navigation("MaritalStateMachine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
