<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebApp.CivilRegistration.Application\WebApp.CivilRegistration.Application.csproj" />
		<ProjectReference Include="..\WebApp.CivilRegistration.Contracts\WebApp.CivilRegistration.Contracts.csproj" />
		<ProjectReference Include="..\WebApp.CivilRegistration.Domain\WebApp.CivilRegistration.Domain.csproj" />
	</ItemGroup>
</Project>
