<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\WebApp.CivilRegistration.Application\WebApp.CivilRegistration.Application.csproj" />
		<ProjectReference Include="..\WebApp.CivilRegistration.Endpoints\WebApp.CivilRegistration.Endpoints.csproj" />
		<ProjectReference Include="..\WebApp.CivilRegistration.Infrastructure\WebApp.CivilRegistration.Infrastructure.csproj" />
	</ItemGroup>
</Project>
