<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebApp.CivilRegistration.Contracts\WebApp.CivilRegistration.Contracts.csproj" />
		<ProjectReference Include="..\WebApp.CivilRegistration.Domain\WebApp.CivilRegistration.Domain.csproj" />
	</ItemGroup>
</Project>
